### Update connector
PUT http://localhost:8083/connectors/demo-connector-last/config
Content-Type: application/json

{
  "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
  "plugin.name": "pgoutput",

  "snapshot.mode": "no_data",
  "slot.name": "debezium_last",

  "database.hostname": "postgres",
  "database.port": "5432",
  "database.user": "demo-debezium",
  "database.password": "demo-debezium",
  "database.dbname" : "demo-debezium",
  "database.server.name": "postgres",
  "table.include.list": "public.dbz_signal,public.dbz_heartbeat,custom.sport,custom.category",

  "topic.prefix": "pgsql.demo",

  "key.converter": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "key.converter.schemas.enable": "false",
  "value.converter.schemas.enable": "false",

  "tombstones.on.delete": "false",

  "transforms": "extractKeyField",

  "transforms.extractKeyField.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
  "transforms.extractKeyField.field": "id",
  "transforms.extractKeyField.predicate": "isCategoryTable",
  "transforms.extractKeyField.negate": "true",
  "predicates": "isCategoryTable",
  "predicates.isCategoryTable.type": "org.apache.kafka.connect.transforms.predicates.TopicNameMatches",
  "predicates.isCategoryTable.pattern": "pgsql.demo.custom.category",

  "publication.autocreate.mode": "filtered",
  "publication.name": "debezium_demo",

  "signal.enabled.channels": "source,kafka",
  "signal.data.collection": "public.dbz_signal",
  "signal.kafka.bootstrap.servers": "kafka:29092",
  "signal.kafka.topic": "pgsql.demo.kafka.signal",

  "heartbeat.interval.ms": "10000",
  "heartbeat.action.query": "INSERT INTO public.dbz_heartbeat (id, ts) VALUES (1, NOW()) ON CONFLICT(id) DO UPDATE SET ts=EXCLUDED.ts;"
}
